import Head from 'next/head';
import Image from 'next/image';
import { SnbForSamlpe } from '../../components/layout/snb';

export default function Home() {
  return (
    <>
      <SnbForSamlpe />
      <div>
        <Head>
          <title>KPP FRONTEND GUIDE</title>
          <meta name='description' content='Generated by create next app' />
        </Head>
      </div>
    </>
  );
}
