import Head from 'next/head';
import { SnbForGuide } from '../../components/layout/snb';
import Example from '../../components/components/Example';
import Code from '../../components/components/Code';

export default function index(props) {
  return (
    <>
      <SnbForGuide />
      <div className='contents-wrapper layout'>
        <Head>
          <title>KPP FRONTEND GUIDE</title>
          <meta name='description' content='Generated by create next app' />
        </Head>
        <section className='page-title'>
          <h3>화면 레이아웃 구조</h3>
          <p>- KPP FRONTEND 의 화면 레이아웃 구조에 대한 설명</p>
        </section>

        <section className='pannel'>
          <div className='pannel-header'>
            <h4>제작 환경 및 사용된 기술</h4>
          </div>
          <div className='pannel-contents'>
            <ul>
              <li>오픈 베타 버전 KPP 앱은 하이브리드로 제작되었습니다.</li>
              <li>
                웹에서도 접근이 가능하고 각각 안드로이드용 앱, IOS용 앱으로도
                배포 될 예정입니다.
              </li>
              <li>
                사용된 프레임워크는 <em> NestJS </em> 이고, 이 밖에 주요
                라이브러리로는 <em> Redux, Axios, MUI </em> 등이 있습니다.
              </li>
            </ul>
          </div>
        </section>

        <section className='pannel'>
          <div className='pannel-header'>
            <h4>기본 레이아웃 구조</h4>
          </div>
          <div className='pannel-contents'>
            <ul>
              <li>
                최근에 사용되고 있는 전형적인 앱의 구조를 그대로 따르고
                있습니다.
              </li>
              <li>
                레이아웃은 크게 상단의 <em> header </em> 와 하단의
                <em> snb </em> 로 이루어져 있습니다.
              </li>
              <li>
                해당 구조에 대한 코드는 별도의 파일로 만들어 /components/layout
                폴더에 기술하였습니다.
              </li>
            </ul>
            <Example
              contents={
                <>
                  <img src='/img/layout.png' alt='레이아웃' />
                  <img src='/img/layout-font.png' alt='레이아웃' />
                </>
              }
            />
          </div>
        </section>

        <section className='pannel'>
          <div className='pannel-header'>
            <h4>풀 페이지 GNB 메뉴</h4>
          </div>
          <div className='pannel-contents'>
            <ul>
              <li>
                GNB 는 <em> Global Navigation Bar </em> 의 약자로 사이트 내의
                전체 이동 경로를 가지고 있는 메뉴 패널을 의미합니다.
              </li>
              <li>
                전체 메뉴는 <em> 별도의 페이지 </em> 를 만들어 기술하였습니다.
              </li>
              <li>GNB 파일은 /menu/gnb.js 입니다.</li>
            </ul>

            <Example
              contents={
                <>
                  <div className='flex-start align-start'>
                    <img src='/img/gnb-menu.png' alt='gnb 메뉴' />
                    <img src='/img/gnb.png' alt='gnb 메뉴 디렉토리' />
                  </div>
                </>
              }
            />
          </div>
        </section>

        <section className='pannel'>
          <div className='pannel-header'>
            <h4>상단 헤더 타입</h4>
          </div>
          <div className='pannel-contents'>
            <ul>
              <li>
                상단 헤더는 <em> 진입한 페이지에 따라 다른 구성 요소 </em> 들을
                가지게 됩니다.
              </li>
              <li>
                헤더의 변화에는 규칙성이 없었기 때문에 기존에 사용하던 단순한
                Components 분기 방법으로는 쉽게 구현하기가 어려웠습니다.
              </li>
              <li>
                이러한 문제를 해결하기 위하여, <em> Redux 의 상태 관리 </em>
                기능을 적극 이용하였습니다.
              </li>
            </ul>

            <ol className='example-list'>
              <li>
                <Example
                  title=' : 메인 페이지 header 스타일'
                  contents={
                    <>
                      <img src='/img/header01.png' alt='헤더01' />

                      <Code
                        contents={`dispatch( 
  setLayoutInfo({
    showSnb: true,
    showHeader: true,
    header: {
      left: 'logo',
      middle: false,
      right: 'bell',
    },
  })
)`}
                      />
                    </>
                  }
                />
              </li>
              <li>
                <Example
                  title=' : GNB 페이지 header 스타일'
                  contents={
                    <>
                      <img src='/img/header02.png' alt='헤더02' />

                      <Code
                        contents={`dispatch(
  setLayoutInfo({
    showSnb: false,
    showHeader: true,
    header: {
      left: 'logo',
      middle: false,
      right: 'settings',
    },
  })
);`}
                      />
                    </>
                  }
                />
              </li>
              <li>
                <Example
                  title=' : 모니터링, 발전소 케어 페이지 header 스타일'
                  contents={
                    <>
                      <img src='/img/header03.png' alt='헤더03' />

                      <Code
                        contents={`dispatch(setNowPageTitle('수익 모니터링'));
dispatch(
  setLayoutInfo({
    showSnb: true,
    showHeader: true,
    header: {
      left: 'logo',
      middle: true,
      right: 'bell',
    },
  })
);`}
                      />
                    </>
                  }
                />
              </li>
              <li>
                <Example
                  title=' : 알림 페이지 header 스타일 - 좌측의 버튼이 단순히 이전
              페이지로 이동'
                  contents={
                    <>
                      <img src='/img/header04.png' alt='헤더04' />

                      <Code
                        contents={`dispatch(setNowPageTitle('수익 통계분석'));
dispatch(
  setLayoutInfo({
    showSnb: false,
    showHeader: true,
    header: {
      left: 'back',
      middle: true,
      right: '',
    },
  })
);`}
                      />
                    </>
                  }
                />
              </li>
              <li>
                <Example
                  title=' : 회원가입, 구독 등의 페이지 header 스타일 - 좌측의 버튼이 이전
                Step 으로 이동하기도 하고, 이전 페이지로 이동하기도 함'
                  contents={
                    <>
                      <img src='/img/header05.png' alt='헤더05' />

                      <Code
                        contents={` dispatch(setNowPageTitle('서비스 이용 약관'));
dispatch(setRouteBeforePageUrl('signin'));
dispatch(
  setLayoutInfo({
    showHeader: true,
    showSnb: false,
    header: {
      left: 'route',
      middle: true,
      right: '',
    },
  })
);`}
                      />
                    </>
                  }
                />
              </li>
              <li>
                <Example
                  title=' : 설정 메뉴의 일부 하위 페이지에서 특정 정보를 수정하는 기능이
                있는 페이지 헤더'
                  contents={
                    <>
                      <img src='/img/header06.png' alt='헤더06' />

                      <Code
                        contents={` dispatch(setNowPageTitle('비밀번호 변경'));
dispatch(
  setLayoutInfo({
    showSnb: false,
    showHeader: true,
    header: {
      left: 'back',
      middle: true,
      right: 'modify',
    },
  })
);`}
                      />
                    </>
                  }
                />
              </li>
            </ol>
          </div>
        </section>

        <section className='pannel'>
          <div className='pannel-header'>
            <h4>특정 페이지에서만 사용이 가능한 형태의 SNB</h4>
          </div>
          <div className='pannel-contents'>
            <ul>
              <li>
                헤더와 마찬가지로
                <em> SNB 는 사용 유무에 있어서 일관성이나 특징이 없어 </em>
                일반적인 방식으로는 표현 할 수가 없었습니다.
              </li>
              <li>
                이를 해결하기 위하여, 상위 패널에서 설명한 헤더 표현 방식과
                마찬가지로 <em> Redux 의 상태관리 </em> 를 적극 활용하였습니다.
              </li>
              <li>
                SNB 의 노출 여부는 페이지의 레이아웃을 담당하는
                <em> setLayoutInfo </em>
                함수를 호출하여 명시하면 됩니다.
              </li>
            </ul>

            <ol classNam='example-list'>
              <li>
                <Example
                  title=' : SNB가 있는 형태'
                  contents={
                    <>
                      <img src='/img/snb.png' alt='snb' />
                      <img src='/img/snb02.png' alt='snb02' />
                      <Code
                        contents={`dispatch(
  setLayoutInfo({
    showSnb: true,
  })
);`}
                      />
                    </>
                  }
                />
              </li>
              <li>
                <Example
                  title=' : SNB가 없는 형태'
                  contents={
                    <>
                      <img src='/img/no-snb.png' alt='snb 없음' />
                      <img src='/img/no-snb02.png' alt='snb 없음02' />
                      <Code
                        contents={`dispatch(
  setLayoutInfo({
    showSnb: false,
  })
);`}
                      />
                    </>
                  }
                />
              </li>
            </ol>
          </div>
        </section>
      </div>
    </>
  );
}
