import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { SnbForGuide } from '../../components/layout/snb';

export default function index(props) {
  return (
    <>
      <SnbForGuide />
      <div>
        <Head>
          <title>KPP FRONTEND GUIDE</title>
          <meta name='description' content='Generated by create next app' />
        </Head>

        <div>1.</div>
      </div>
    </>
  );
}
