import React, { useState } from 'react';
import Head from 'next/head';
import Example from '../../../components/components/Example';
import Code from '../../../components/components/Code';
import { SnbForSamlpe } from '../../../components/layout/snb';
import {
  NewDottedBadge,
  NewLetterBadge,
} from '../../../components/UI/atoms/Badge';
import { CustomIconButton } from '../../../components/UI/atoms/Button';

export default function Badge(props) {
  const [nowstep, setNowStep] = useState(1);

  return (
    <>
      <SnbForSamlpe />
      <div className='contents-wrapper layout'>
        <Head>
          <title>KPP BADGE SAMPLE</title>
          <meta name='description' content='Generated by create next app' />
        </Head>
        <section className='page-title'>
          <h3>KPP BADGE SAMPLE</h3>
          <p>- KPP PROJECT 에서 곳곳에 쓰이는 알림을 알리는 용도의 뱃지</p>
        </section>

        <section className='pannel'>
          <div className='pannel-header'>
            <h4>New Letter Badge</h4>
          </div>
          <div className='pannel-contents'>
            <ul>
              <li>N 로고가 중앙에 들어간 알림 뱃지 입니다.</li>
              <li>주로 GNB 메뉴의 글씨 옆에 붙는 용도로 사용됩니다.</li>
            </ul>
            <Example
              title=' : 기본 New Letter Badge 호출'
              className='none-border'
              contents={
                <>
                  <NewLetterBadge />
                  <Code
                    contents={`import { NewLetterBadge } from '../../../components/UI/atoms/Badge';

<NewLetterBadge />`}
                  />
                </>
              }
            />
          </div>
        </section>

        <section className='pannel'>
          <div className='pannel-header'>
            <h4>New Dotted Badge</h4>
          </div>
          <div className='pannel-contents'>
            <ul>
              <li>글씨 주변부에 올라가는 작은 점 모양의 알림 뱃지 입니다.</li>
              <li>주로 알림 메뉴의 벨 아이콘 옆에 붙는 용도로 사용됩니다.</li>
            </ul>
            <Example
              title=' : 기본 New Dotted Badge 호출'
              className='none-border'
              contents={
                <>
                  <span className='header-bell-wrapper'>
                    <NewDottedBadge />
                    <CustomIconButton
                      className='bell-icon'
                      icon={
                        <img
                          src='/img/header/header-bell.svg'
                          className='bell-icon'
                          alt='종 모양 알림 아이콘'
                        />
                      }
                      aria-label='종 모양 알림 아이콘'
                    />
                  </span>
                  <Code
                    contents={`import { NewDottedBadge } from '../../../components/UI/atoms/Badge';
                    
 <span className='header-bell-wrapper'>
    <NewDottedBadge />
    <CustomIconButton
      className='bell-icon'
      icon={
        <img
          src='/img/header/header-bell.svg'
          className='bell-icon'
          alt='종 모양 알림 아이콘'
        />
      }
      aria-label='종 모양 알림 아이콘'
    />
  </span>`}
                  />
                </>
              }
            />
          </div>
        </section>

        <section className='pannel'>
          <div className='pannel-header'>
            <h4>Sub Status Badge</h4>
          </div>
          <div className='pannel-contents'>
            <ul>
              <li>발전소 리스트의 구독 상태를 알리는 라벨형 뱃지 입니다.</li>
              <li>
                내가 등록한 발전소의 상태를 직관적으로 알리는 용도로 사용됩니다.
              </li>
            </ul>
            <Example
              title=' : 다양한 종류의 구독 라벨의 모습'
              className='none-border'
              contents={
                <>
                  <img src='/img/label.png' lat='구독 라벨' />
                  <Code
                    contents={`import { SubStatusBadge } from '../../../components/UI/atoms/Badge';
                    
<SubStatusBadge 
  status='received'
              // received(접수완료)
              // inspect(상세검토)
              // completed(구독완료)
              // subscribe(구독)
              // brokerage(전력중개사업)
/>`}
                  />
                </>
              }
            />
          </div>
        </section>
      </div>
    </>
  );
}
