import React, { useState } from 'react';
import Head from 'next/head';
import Example from '../../../components/components/Example';
import Code from '../../../components/components/Code';
import { SnbForSamlpe } from '../../../components/layout/snb';
import DefaultButton, {
  KakaoLoginButton,
  NaverLoginButton,
  NextStepButton,
} from '../../../components/UI/atoms/Button';

export default function Button(props) {
  const [nowstep, setNowStep] = useState(1);

  return (
    <>
      <SnbForSamlpe />
      <div className='contents-wrapper layout'>
        <Head>
          <title>KPP BUTTON SAMPLE</title>
          <meta name='description' content='Generated by create next app' />
        </Head>
        <section className='page-title'>
          <h3>KPP BUTTON SAMPLE</h3>
          <p>
            - KPP PROJECT 에서 자주 사용 되는 버튼을 컴포넌트로 만들어 재사용
            했습니다.
          </p>
        </section>
        <section className='pannel'>
          <div className='pannel-header'>
            <h4>Default Button</h4>
          </div>
          <div className='pannel-contents'>
            <ul>
              <li>가장 많이 사용 하는 형태의 버튼을 컴포넌트화 했습니다.</li>
              <li>
                id, className, text, onClick 등의 간단한 props 요소들을 이용하여
                여러 형태의 버튼으로 응용하여 사용 할 수 있습니다.
              </li>
            </ul>
            <Example
              title=' : 기본 Button 호출'
              contents={
                <>
                  <DefaultButton
                    id='test'
                    className='test'
                    text='기본 유형의 버튼 : 클릭해 보세요!'
                    onClick={() => alert('테스트 입니다! :-D')}
                  />
                  <Code
                    contents={`import DefaultButton from '../../../components/UI/atoms/Button';
<DefaultButton 
  id='test'
  className='test'
  text='기본 유형의 버튼 : 클릭해 보세요!'
  onClick={() => alert('테스트 입니다! :-D')}
/>`}
                  />
                </>
              }
            />
          </div>
        </section>
        <section className='pannel'>
          <div className='pannel-header'>
            <h4>KAKAO LOGIN BUTTON SAMPLE</h4>
          </div>

          <div className='pannel-contents'>
            <ul>
              <li>카카오 로그인 버튼 입니다.</li>
            </ul>
            <Example
              title=' : KaKao Login Button 호출'
              contents={
                <>
                  <KakaoLoginButton />
                  <Code
                    contents={`import KakaoLoginButton from '../../../components/UI/atoms/Button';
 <KakaoLoginButton />`}
                  />
                </>
              }
            />
          </div>
        </section>
        <section className='pannel'>
          <div className='pannel-header'>
            <h4>NAVER LOGIN BUTTON SAMPLE</h4>
          </div>

          <div className='pannel-contents'>
            <ul>
              <li>네이버 로그인 버튼입니다.</li>
            </ul>
            <Example
              title=' : Naver Login Button 호출'
              contents={
                <>
                  <NaverLoginButton />
                  <Code
                    contents={`import NaverLoginButton from '../../../components/UI/atoms/Button';
<NaverLoginButton />`}
                  />
                </>
              }
            />
          </div>
        </section>
        <section className='pannel'>
          <div className='pannel-header'>
            <h4>NAVER LOGIN BUTTON SAMPLE</h4>
          </div>

          <div className='pannel-contents'>
            <ul>
              <li>스텝형 PAGE UI 에서 쓰이는 하단의 진행 버튼</li>
            </ul>
            <Example
              title=' : 스텝형 PAGE UI 진행 Button 호출'
              contents={
                <>
                  <NextStepButton
                    className={nowstep > 4 ? 'active' : ''}
                    onClick={() => setNowStep(nowstep + 1)}
                    text={nowstep > 4 ? '확인' : '버튼을 4회 눌러보세요!'}
                  />
                  <NextStepButton className='active' text='확인' />
                  <Code
                    contents={`import NextStepButton from '../../../components/UI/atoms/Button';

<NextStepButton
  className={nowstep > 4 ? 'active' : ''}
  onClick={() => setNowStep(nowstep + 1)}
  text={nowstep > 4 ? '확인' : ''}
/>
<NextStepButton className='active' text='확인' />`}
                  />
                </>
              }
            />
          </div>
        </section>
      </div>
    </>
  );
}
