import React, { useState } from 'react';
import Head from 'next/head';
import Example from '../../../components/components/Example';
import Code from '../../../components/components/Code';
import { SnbForSamlpe } from '../../../components/layout/snb';
import { BasicSwitch } from '../../../components/UI/atoms/Switch';

export default function Switch(props) {
  return (
    <>
      <SnbForSamlpe />
      <div className='contents-wrapper layout'>
        <Head>
          <title>KPP SWITCH SAMPLE</title>
          <meta name='description' content='Generated by create next app' />
        </Head>
        <section className='page-title'>
          <h3>KPP SWITCH SAMPLE</h3>
          <p>
            - KPP PROJECT 에서 자주 사용 되는 SWITCH UI 를 컴포넌트로 만들어
            재사용 했습니다.
          </p>
        </section>

        <section className='pannel'>
          <div className='pannel-header'>
            <h4>Basic Switch</h4>
          </div>
          <div className='pannel-contents'>
            <ul>
              <li>가장 많이 사용 하는 형태의 스위치를 컴포넌트화 했습니다.</li>
              <li>
                CSS 를 조금 변경하는 것만으로도 다양한 형태의 스위치로 응용하여
                사용 할 수 있습니다
              </li>
              <li>
                하지만, 완전히 새로운 형태의 디자인이 나오면 새로운 컴포넌트를
                만들어야 합니다.
              </li>
            </ul>
            <Example
              title=' : Basic Switch 호출'
              contents={
                <>
                  <div className='flex-start align-start'>
                    <BasicSwitch />
                  </div>
                  <Code
                    contents={`import { BasicSwitch } from '../../../components/UI/atoms/Switch';

<BasicSwitch />`}
                  />
                </>
              }
            />
          </div>
        </section>
      </div>
    </>
  );
}
