import React, { useState } from 'react';
import Head from 'next/head';
import Example from '../../../components/components/Example';
import Code from '../../../components/components/Code';
import { SnbForSamlpe } from '../../../components/layout/snb';
import {
  DefaultTextInput,
  ResetTextInput,
  SearchInput,
} from '../../../components/UI/atoms/TextInput';

export default function TextInput(props) {
  return (
    <>
      <SnbForSamlpe />
      <div className='contents-wrapper layout'>
        <Head>
          <title>KPP TEXTINPUT SAMPLE</title>
          <meta name='description' content='Generated by create next app' />
        </Head>
        <section className='page-title'>
          <h3>KPP TEXTINPUT SAMPLE</h3>
          <p>
            - KPP PROJECT 에서 자주 사용 되는 TEXT INPUT UI 를 컴포넌트로 만들어
            재사용 했습니다.
          </p>
        </section>
        <section className='pannel'>
          <div className='pannel-header'>
            <h4>Default Text Input</h4>
          </div>
          <div className='pannel-contents'>
            <ul>
              <li>
                가장 많이 사용 하는 형태의 텍스트 인풋을 컴포넌트화 했습니다.
              </li>
              <li>
                CSS 를 조금 변경하는 것만으로도 다양한 형태의 텍스트 인풋으로
                응용하여 사용 할 수 있습니다
              </li>
              <li>
                하지만, 완전히 새로운 형태의 디자인이 나오면 새로운 컴포넌트를
                만들어야 합니다.
              </li>
            </ul>
            <Example
              title=' : Default Text Input 호출'
              contents={
                <>
                  <div className='flex-start align-start'>
                    <DefaultTextInput placeholder='테스트!' />
                  </div>
                  <Code
                    contents={`import { DefaultTextInput } from '../../../components/UI/atoms/TextInput';

<DefaultTextInput />`}
                  />
                </>
              }
            />
          </div>
        </section>
        <section className='pannel'>
          <div className='pannel-header'>
            <h4>Reset Text Input</h4>
          </div>
          <div className='pannel-contents'>
            <ul>
              <li>
                상단에 Placehoder 가 유지되면서, 동시에 리셋 버튼이 있는 형태의
                텍스트 인풋 컴포넌트입니다.
              </li>
              <li>
                글을 쓰기 전에는 보이지 않던 리셋 버튼이, 입력값이 하나 이상인
                경우 우측 끝에 나타납니다.
              </li>
              <li>
                포커스가 들어가 있는 상태, 혹은 글을 쓰고 있는 중에는 상단에
                placeholder 가 유지됩니다.
              </li>
            </ul>
            <Example
              title=' : Reset Text Input 호출'
              contents={
                <>
                  <div className='flex-start align-start'>
                    <ResetTextInput
                      placeholder='label 값이 없는 경우에는 이 글씨가 보이지만, 상단에 유지되는 placeholder 로 작동되지 않습니다!'
                      label='유지되는 글'
                    />
                  </div>
                  <Code
                    contents={`import { ResetTextInput } from '../../../components/UI/atoms/TextInput';

<ResetTextInput
  placeholder='label 값이 없는 경우에는 이 글씨가 보이지만, 상단에 유지되는 placeholder 로 작동되지 않습니다!'
  label='유지되는 글'
/>`}
                  />
                </>
              }
            />
          </div>
        </section>
        <section className='pannel'>
          <div className='pannel-header'>
            <h4>Search Input</h4>
          </div>
          <div className='pannel-contents'>
            <ul>
              <li>검색을 위한 텍스트 인풋 박스입니다.</li>
            </ul>
            <Example
              title=' : Search Input 호출'
              contents={
                <>
                  <div className='flex-start align-start'>
                    <SearchInput placeholder='내 발전소 검색' />
                  </div>
                  <Code
                    contents={`import { SearchInput } from '../../../components/UI/atoms/TextInput';

<SearchInput placeholder='내 발전소 검색' />`}
                  />
                </>
              }
            />
          </div>
        </section>
      </div>
    </>
  );
}
