import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>KPP FRONTEND GUIDE</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
    </div>
  );
}
